gtitle = [{"text": "Forrest Gump", "size": 100},
{"text": "Pulp Fiction", "size": 93},
{"text": "\"Shawshank Redemption, The\"", "size": 89},
{"text": "\"Silence of the Lambs, The\"", "size": 86},
{"text": "Star Wars: Episode IV - A New Hope", "size": 82},
{"text": "Jurassic Park", "size": 75},
{"text": "\"Matrix, The\"", "size": 70},
{"text": "Toy Story", "size": 66},
{"text": "Schindler's List", "size": 65},
{"text": "Terminator 2: Judgment Day", "size": 62},
{"text": "Star Wars: Episode V - The Empire Strikes Back", "size": 61},
{"text": "Braveheart", "size": 59},
{"text": "Back to the Future", "size": 58},
{"text": "Fargo", "size": 58},
{"text": "Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark)", "size": 56},
{"text": "American Beauty", "size": 56},
{"text": "Independence Day (a.k.a. ID4)", "size": 55},
{"text": "Star Wars: Episode VI - Return of the Jedi", "size": 55},
{"text": "Aladdin", "size": 54},
{"text": "\"Fugitive, The\"", "size": 54},
{"text": "Dances with Wolves", "size": 50},
{"text": "Fight Club", "size": 50},
{"text": "Seven (a.k.a. Se7en)", "size": 49},
{"text": "\"Usual Suspects, The\"", "size": 49},
{"text": "Apollo 13", "size": 49},
{"text": "\"Lion King, The\"", "size": 49},
{"text": "\"Godfather, The\"", "size": 49},
{"text": "\"Lord of the Rings: The Fellowship of the Ring, The\"", "size": 49},
{"text": "True Lies", "size": 48},
{"text": "Twelve Monkeys (a.k.a. 12 Monkeys)", "size": 47},
{"text": "\"Sixth Sense, The\"", "size": 46},
{"text": "Saving Private Ryan", "size": 46},
{"text": "Men in Black (a.k.a. MIB)", "size": 45},
{"text": "\"Lord of the Rings: The Two Towers, The\"", "size": 45},
{"text": "Speed", "size": 42},
{"text": "Beauty and the Beast", "size": 40},
{"text": "\"Lord of the Rings: The Return of the King, The\"", "size": 40},
{"text": "Ace Ventura: Pet Detective", "size": 40},
{"text": "Shrek", "size": 40},
{"text": "Mission: Impossible", "size": 37},
{"text": "Groundhog Day", "size": 36},
{"text": "\"Princess Bride, The\"", "size": 36},
{"text": "E.T. the Extra-Terrestrial", "size": 35},
{"text": "Dumb & Dumber (Dumb and Dumber)", "size": 34},
{"text": "\"Terminator, The\"", "size": 34},
{"text": "\"Mask, The\"", "size": 33},
{"text": "Good Will Hunting", "size": 33},
{"text": "Mrs. Doubtfire", "size": 32},
{"text": "Die Hard", "size": 31},
{"text": "Twister", "size": 31},
{"text": "Babe", "size": 30},
{"text": "Willy Wonka & the Chocolate Factory", "size": 30},
{"text": "Pretty Woman", "size": 30},
{"text": "Indiana Jones and the Last Crusade", "size": 30},
{"text": "Ghostbusters (a.k.a. Ghost Busters)", "size": 30},
{"text": "Blade Runner", "size": 30},
{"text": "Stargate", "size": 29},
{"text": "Monty Python and the Holy Grail", "size": 29},
{"text": "One Flew Over the Cuckoo's Nest", "size": 29},
{"text": "Die Hard: With a Vengeance", "size": 28},
{"text": "Pirates of the Caribbean: The Curse of the Black Pearl", "size": 28},
{"text": "Star Wars: Episode I - The Phantom Menace", "size": 27},
{"text": "\"Truman Show, The\"", "size": 26},
{"text": "\"Rock, The\"", "size": 26},
{"text": "\"Godfather: Part II, The\"", "size": 26},
{"text": "Spider-Man", "size": 25},
{"text": "Ferris Bueller's Day Off", "size": 25},
{"text": "L\u00e9on: The Professional (a.k.a. The Professional) (L\u00e9on)", "size": 25},
{"text": "Reservoir Dogs", "size": 25},
{"text": "Memento", "size": 25},
{"text": "Goodfellas", "size": 24},
{"text": "\"Monsters, Inc.\"", "size": 24},
{"text": "Ocean's Eleven", "size": 24},
{"text": "Batman Forever", "size": 23},
{"text": "Home Alone", "size": 23},
{"text": "Alien", "size": 23},
{"text": "X-Men", "size": 23},
{"text": "Ghost", "size": 22},
{"text": "Being John Malkovich", "size": 22},
{"text": "\"Incredibles, The\"", "size": 22},
{"text": "Interview with the Vampire: The Vampire Chronicles", "size": 22},
{"text": "Sleepless in Seattle", "size": 22},
{"text": "Aliens", "size": 22},
{"text": "L.A. Confidential", "size": 22},
{"text": "Toy Story 2", "size": 22},
{"text": "\"Amelie (Fabuleux destin d'Am\u00e9lie Poulain, Le)\"", "size": 22},
{"text": "Trainspotting", "size": 22},
{"text": "2001: A Space Odyssey", "size": 21},
{"text": "There's Something About Mary", "size": 21},
{"text": "GoldenEye", "size": 21},
{"text": "Four Weddings and a Funeral", "size": 21},
{"text": "Finding Nemo", "size": 21},
{"text": "\"Clockwork Orange, A\"", "size": 21},
{"text": "Shakespeare in Love", "size": 21},
{"text": "\"Dark Knight, The\"", "size": 21},
{"text": "Clueless", "size": 20},
{"text": "\"Big Lebowski, The\"", "size": 20},
{"text": "Rain Man", "size": 20},
{"text": "Taxi Driver", "size": 20},
{"text": "\"Fifth Element, The\"", "size": 20}
];
